CREATE DATABASE E_COMMR_PROJ
USE E_COMMR_PROJ;

-----QUERRY 1----
SELECT 
    FORMAT(o.order_purchase_timestamp, 'yyyy-MM') AS month,
    ROUND(SUM(p.payment_value), 3) AS monthly_revenue
FROM 
    Payments p
JOIN 
    Orders o ON p.order_id = o.order_id
GROUP BY 
    FORMAT(o.order_purchase_timestamp, 'yyyy-MM')
ORDER BY 
    month;

----QUERRY 2----
 SELECT TOP 10
    P.PRODUCT_CATEGORY_NAME,
    COUNT(OI.ORDER_ID) AS TOTAL_QUANTITY_SOLD,
 ROUND(SUM(OI.PRICE),0) AS TOTAL_REVENUE
 FROM 
    ORDER_ITEMS OI
 JOIN 
    ORDERS O ON OI.ORDER_ID = O.ORDER_ID
 JOIN 
    PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
 WHERE 
    O.ORDER_STATUS = 'DELIVERED'
 GROUP BY 
    P.PRODUCT_CATEGORY_NAME
 ORDER BY 2 DESC;

----QUERRY 3----
CREATE NONCLUSTERED INDEX X_PAYMENT_VALUES 
ON PAYMENTS (PAYMENT_VALUE);
 SELECT 
ROUND(AVG(PAYMENT_VALUE),2) AS AVG_AMOUNT_PER_ORDER
 FROM 
PAYMENTS;
 SELECT 
P.PRODUCT_CATEGORY_NAME,
 PM.PAYMENT_TYPE,
 ROUND(AVG(OI.PRICE), 2) AS AVG_SPENT_PER_ITEM
 FROM 
ORDER_ITEMS OI
 JOIN 
PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
 JOIN 
PAYMENTS PM ON OI.ORDER_ID = PM.ORDER_ID
 GROUP BY 
P.PRODUCT_CATEGORY_NAME,
 PM.PAYMENT_TYPE
 ORDER BY 
P.PRODUCT_CATEGORY_NAME,
 AVG_SPENT_PER_ITEM DESC;

---QUERRY 4---
 SELECT 
    COUNT(DISTINCT SELLER_ID) AS ACTIVE_SELLERS
 FROM 
    ORDER_ITEMS;
 SELECT 
    FORMAT(O.ORDER_PURCHASE_TIMESTAMP, 'yyyy-MM') AS PURCHASE_MONTH,
    COUNT(DISTINCT OI.SELLER_ID) AS ACTIVE_SELLERS
 FROM 
    ORDER_ITEMS OI
 JOIN 
    ORDERS O ON OI.ORDER_ID = O.ORDER_ID
 WHERE 
    O.ORDER_STATUS = 'delivered'
 GROUP BY 
    FORMAT(O.ORDER_PURCHASE_TIMESTAMP, 'yyyy-MM')
 ORDER BY 
    PURCHASE_MONTH;

----QUERRY 5------
 SELECT TOP 10
    P.PRODUCT_CATEGORY_NAME,
    COUNT(OI.ORDER_ID) AS TOTAL_QUANTITY_SOLD
 FROM 
    ORDER_ITEMS OI
 JOIN 
    ORDERS O ON OI.ORDER_ID = O.ORDER_ID
 JOIN 
    PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
 WHERE 
    O.ORDER_STATUS = 'DELIVERED'
 GROUP BY 
    P.PRODUCT_CATEGORY_NAME
 ORDER BY 2 DESC;
 SELECT 
    FORMAT(O.ORDER_PURCHASE_TIMESTAMP, 'yyyy-MM') AS MONTH,
    P.PRODUCT_CATEGORY_NAME,
    COUNT(OI.ORDER_ID) AS TOTAL_QUANTITY_SOLD
 FROM 
    ORDER_ITEMS OI
 JOIN 
    ORDERS O ON OI.ORDER_ID = O.ORDER_ID
 JOIN 
    PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
 WHERE 
    O.ORDER_STATUS = 'DELIVERED' AND P.PRODUCT_CATEGORY_NAME IS NOT NULL
 GROUP BY 
    FORMAT(O.ORDER_PURCHASE_TIMESTAMP, 'yyyy-MM'),
    P.PRODUCT_CATEGORY_NAME
 ORDER BY 3 desc;

---QUERRY 6---

 SELECT 
    R.REVIEW_SCORE,
    COUNT(OI.ORDER_ID) AS TOTAL_ORDERS,
    COUNT(DISTINCT OI.PRODUCT_ID) AS DISTINCT_PRODUCTS,
    SUM(OI.PRICE) AS TOTAL_REVENUE,
    AVG(OI.PRICE) AS AVG_PRICE
 FROM 
    REVIEW R
 JOIN 
    ORDER_ITEMS OI ON R.ORDER_ID = OI.ORDER_ID
 GROUP BY 
    R.REVIEW_SCORE
 ORDER BY 
    R.REVIEW_SCORE;